# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a6234abefc93078c7ebee1a997a7e5db91013eed53e742f3231598c9090cc829a58408df221b0d1a08c80a03e1ce675530a35005edf138777f8bbbd12504d4f

test:
  secret_key_base: 52301138b3c4ef2c5e43ae144cad26ff8635d2d1b53f99d89d43ef5f650f6759cadd0291dc8b9cbf07efee5371240a0c8fcf475c20ae412236021022dc4f855f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
